# Generated by Django 5.2.3 on 2025-09-27 19:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('superadmin', '0002_databasebackup_globalnotification_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=50, unique=True)),
                ('specialization', models.CharField(choices=[('technical', 'Technical Support'), ('billing', 'Billing Support'), ('general', 'General Support'), ('escalation', 'Escalation Specialist'), ('training', 'Training Specialist')], default='general', max_length=20)),
                ('level', models.CharField(choices=[('junior', 'Junior Support'), ('senior', 'Senior Support'), ('lead', 'Lead Support'), ('manager', 'Support Manager')], default='junior', max_length=20)),
                ('total_tickets_resolved', models.IntegerField(default=0)),
                ('average_resolution_time', models.FloatField(default=0.0)),
                ('customer_satisfaction_rating', models.FloatField(default=0.0)),
                ('escalation_rate', models.FloatField(default=0.0)),
                ('max_concurrent_tickets', models.IntegerField(default=10)),
                ('current_ticket_count', models.IntegerField(default=0)),
                ('is_available', models.BooleanField(default=True)),
                ('working_hours_start', models.TimeField(default='09:00')),
                ('working_hours_end', models.TimeField(default='17:00')),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('certifications', models.JSONField(blank=True, default=list)),
                ('languages_spoken', models.JSONField(blank=True, default=list)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('emergency_contact', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_staff', to='superadmin.tenant')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='support_staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__first_name', 'user__last_name'],
            },
        ),
        migrations.CreateModel(
            name='SupportTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('team_sla_target', models.FloatField(default=24.0)),
                ('team_satisfaction_target', models.FloatField(default=4.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('members', models.ManyToManyField(blank=True, related_name='teams', to='SupportTicket.supportstaff')),
                ('team_lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_teams', to='SupportTicket.supportstaff')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_teams', to='superadmin.tenant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SupportAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_tickets', models.IntegerField(default=0)),
                ('open_tickets', models.IntegerField(default=0)),
                ('resolved_tickets', models.IntegerField(default=0)),
                ('closed_tickets', models.IntegerField(default=0)),
                ('average_response_time', models.FloatField(default=0.0)),
                ('average_resolution_time', models.FloatField(default=0.0)),
                ('customer_satisfaction', models.FloatField(default=0.0)),
                ('escalation_rate', models.FloatField(default=0.0)),
                ('active_support_staff', models.IntegerField(default=0)),
                ('total_support_hours', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_analytics', to='superadmin.tenant')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('tenant', 'date')},
            },
        ),
        migrations.CreateModel(
            name='SupportSLA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical'), ('urgent', 'Urgent')], max_length=20)),
                ('category', models.CharField(blank=True, choices=[('technical', 'Technical'), ('billing', 'Billing'), ('account', 'Account'), ('appointments', 'Appointments'), ('reports', 'Reports'), ('equipment', 'Equipment'), ('data_export', 'Data Export'), ('notifications', 'Notifications'), ('general', 'General')], max_length=20, null=True)),
                ('first_response_time', models.FloatField(help_text='First response time in hours')),
                ('resolution_time', models.FloatField(help_text='Resolution time in hours')),
                ('escalation_time', models.FloatField(help_text='Escalation time in hours')),
                ('escalation_level', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_slas', to='superadmin.tenant')),
            ],
            options={
                'ordering': ['priority', 'category'],
                'unique_together': {('tenant', 'priority', 'category')},
            },
        ),
    ]
