# Generated by Django 5.2.5 on 2025-09-04 09:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovedDoctorVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_id', models.CharField(max_length=100, unique=True)),
                ('assigned_staff', models.CharField(max_length=255)),
                ('patient_name', models.CharField(blank=True, max_length=255)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('postal_code', models.CharField(blank=True, max_length=50)),
                ('reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('medical_needs', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(default='Approved', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approved_doctor_visits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ApprovedPatientVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_id', models.CharField(max_length=100, unique=True)),
                ('assigned_staff', models.CharField(max_length=255)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('postal_code', models.CharField(blank=True, max_length=50)),
                ('doctor_name', models.CharField(blank=True, max_length=255)),
                ('reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('medical_needs', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(default='Approved', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approved_patient_visits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
