# Generated by Django 5.2.5 on 2025-09-04 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeVisitRequests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approveddoctorvisit',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='approveddoctorvisit',
            name='assigned_staff',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='approveddoctorvisit',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='approveddoctorvisit',
            name='medical_needs',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='approveddoctorvisit',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='approveddoctorvisit',
            name='patient_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='approveddoctorvisit',
            name='postal_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='approveddoctorvisit',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='approvedpatientvisit',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='approvedpatientvisit',
            name='assigned_staff',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='approvedpatientvisit',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='approvedpatientvisit',
            name='doctor_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='approvedpatientvisit',
            name='medical_needs',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='approvedpatientvisit',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='approvedpatientvisit',
            name='postal_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='approvedpatientvisit',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
