# Generated by Django 5.2.5 on 2025-09-10 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TenantUser',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('doctor', 'Doctor'), ('technician', 'Technician'), ('support', 'Support Staff')], max_length=50)),
                ('branch', models.CharField(blank=True, choices=[('main', 'Main Branch'), ('west', 'West Branch'), ('east', 'East Branch')], max_length=50, null=True)),
                ('password', models.CharField(max_length=128)),
                ('created_by', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant_id', models.IntegerField()),
            ],
        ),
    ]
