# Generated by Django 5.2.5 on 2025-09-27 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ManageUsers', '0001_initial'),
    ]

    operations = [
    ]
