# Generated by Django 5.2.3 on 2025-09-27 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManageUsers', '0002_auto_20250927_1503'),
        ('superadmin', '0002_databasebackup_globalnotification_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenantuser',
            name='tenant_id',
        ),
        migrations.AddField(
            model_name='tenantuser',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='superadmin.tenant'),
            preserve_default=False,
        ),
    ]
