# Generated by Django 5.2.5 on 2025-09-02 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientName', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('postalCode', models.CharField(blank=True, max_length=20, null=True)),
                ('doctor', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
                ('reason', models.TextField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('assignedStaff', models.CharField(blank=True, max_length=200, null=True)),
                ('medicalNeeds', models.JSONField(default=list)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
