# Generated by Django 5.2.5 on 2025-08-28 09:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testrequest',
            name='date_requested',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='testrequest',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testrequest',
            name='patient_id',
            field=models.CharField(default='UNKNOWN', max_length=50),
        ),
        migrations.AddField(
            model_name='testrequest',
            name='priority',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Urgent', 'Urgent'), ('Critical', 'Critical')], default='Normal', max_length=20),
        ),
        migrations.AlterField(
            model_name='testrequest',
            name='patient_name',
            field=models.CharField(default='UNKNOWN', max_length=255),
        ),
        migrations.AlterField(
            model_name='testrequest',
            name='test_type',
            field=models.CharField(default='General', max_length=255),
        ),
    ]
