# Generated by Django 5.2.5 on 2025-09-25 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0003_equipment_faqcategory_inventorycategory_supplier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Pending', max_length=20),
        ),
    ]
