# Generated by Django 4.2.7 on 2025-09-29 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0009_branch'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Branch',
        ),
    ]
