# Generated by Django 4.2.7 on 2025-09-29 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0010_delete_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='testrequest',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
