# Generated by Django 5.2.5 on 2025-09-27 15:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('superadmin', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingEntry',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
                ('entry_type', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense'), ('asset', 'Asset'), ('liability', 'Liability'), ('equity', 'Equity')], max_length=20)),
                ('category', models.CharField(choices=[('patient_fees', 'Patient Fees'), ('insurance_payments', 'Insurance Payments'), ('consultation_fees', 'Consultation Fees'), ('test_fees', 'Test Fees'), ('other_income', 'Other Income'), ('salaries', 'Salaries'), ('rent', 'Rent'), ('utilities', 'Utilities'), ('medical_supplies', 'Medical Supplies'), ('equipment', 'Equipment'), ('maintenance', 'Maintenance'), ('marketing', 'Marketing'), ('insurance', 'Insurance'), ('other_expenses', 'Other Expenses')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('check', 'Check'), ('card', 'Card'), ('bank_transfer', 'Bank Transfer'), ('insurance', 'Insurance'), ('other', 'Other')], max_length=20)),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True)),
                ('account', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('receipt_file', models.FileField(blank=True, null=True, upload_to='receipts/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounting_entries', to='superadmin.tenant')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FinancialReport',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('income_statement', 'Income Statement'), ('balance_sheet', 'Balance Sheet'), ('cash_flow', 'Cash Flow Statement'), ('profit_loss', 'Profit & Loss'), ('monthly_summary', 'Monthly Summary'), ('yearly_summary', 'Yearly Summary')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('data', models.JSONField(default=dict)),
                ('total_income', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('net_profit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_reports', to='superadmin.tenant')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
    ]
