# Generated by Django 5.2.3 on 2025-09-27 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('superadmin', '0002_databasebackup_globalnotification_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Culture',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('patient_name', models.CharField(max_length=255)),
                ('patient_id', models.CharField(max_length=50)),
                ('specimen_type', models.CharField(choices=[('blood', 'Blood'), ('urine', 'Urine'), ('sputum', 'Sputum'), ('stool', 'Stool'), ('wound_swab', 'Wound Swab'), ('throat_swab', 'Throat Swab'), ('cerebrospinal_fluid', 'Cerebrospinal Fluid'), ('tissue', 'Tissue'), ('other', 'Other')], max_length=50)),
                ('culture_type', models.CharField(choices=[('bacterial', 'Bacterial Culture'), ('fungal', 'Fungal Culture'), ('viral', 'Viral Culture'), ('mycobacterial', 'Mycobacterial Culture'), ('mixed', 'Mixed Culture')], max_length=50)),
                ('organism', models.CharField(blank=True, max_length=255, null=True)),
                ('collection_date', models.DateField()),
                ('technician', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('report_date', models.DateField(blank=True, null=True)),
                ('created_by', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cultures', to='superadmin.tenant')),
            ],
            options={
                'ordering': ['-collection_date'],
                'unique_together': {('patient_id', 'collection_date', 'specimen_type', 'tenant')},
            },
        ),
        migrations.CreateModel(
            name='AntibioticSensitivity',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('antibiotic_name', models.CharField(max_length=255)),
                ('sensitivity', models.CharField(choices=[('sensitive', 'Sensitive'), ('intermediate', 'Intermediate'), ('resistant', 'Resistant'), ('not_tested', 'Not Tested')], max_length=20)),
                ('mic_value', models.CharField(blank=True, max_length=50, null=True)),
                ('zone_diameter', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('tested_date', models.DateField()),
                ('created_by', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='antibiotic_sensitivities', to='superadmin.tenant')),
                ('culture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='antibiotic_sensitivities', to='CulturesAntibiotics.culture')),
            ],
            options={
                'ordering': ['antibiotic_name'],
                'unique_together': {('culture', 'antibiotic_name')},
            },
        ),
    ]
