# Generated by Django 5.2.3 on 2025-09-27 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('superadmin', '0002_databasebackup_globalnotification_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('specialty', models.CharField(choices=[('cardiology', 'Cardiology'), ('neurology', 'Neurology'), ('pediatrics', 'Pediatrics'), ('orthopedics', 'Orthopedics'), ('dermatology', 'Dermatology'), ('internal_medicine', 'Internal Medicine'), ('surgery', 'Surgery'), ('radiology', 'Radiology'), ('pathology', 'Pathology'), ('anesthesiology', 'Anesthesiology')], max_length=50)),
                ('license_number', models.CharField(max_length=100, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('experience', models.CharField(blank=True, max_length=100, null=True)),
                ('education', models.TextField(blank=True, null=True)),
                ('schedule', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending'), ('suspended', 'Suspended')], default='active', max_length=20)),
                ('total_patients', models.IntegerField(default=0)),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('join_date', models.DateField(auto_now_add=True)),
                ('created_by', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='superadmin.tenant')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('email', 'tenant')},
            },
        ),
    ]
