# Generated by Django 5.2.3 on 2025-09-27 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DoctorManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='created_by',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
