# Generated by Django 5.2.3 on 2025-09-27 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DoctorManagement', '0002_alter_doctor_created_by'),
        ('superadmin', '0002_databasebackup_globalnotification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='can_order_tests',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='can_prescribe',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='can_review_results',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='certification_level',
            field=models.CharField(choices=[('board_certified', 'Board Certified'), ('board_eligible', 'Board Eligible'), ('resident', 'Resident'), ('fellow', 'Fellow'), ('attending', 'Attending')], default='board_certified', max_length=20),
        ),
        migrations.AddField(
            model_name='doctor',
            name='consultation_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='doctor',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='languages_spoken',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='doctor',
            name='max_daily_appointments',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='doctor',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='requires_supervision',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='doctor',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_doctors', to='DoctorManagement.doctor'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='years_experience',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialty',
            field=models.CharField(choices=[('cardiology', 'Cardiology'), ('neurology', 'Neurology'), ('pediatrics', 'Pediatrics'), ('orthopedics', 'Orthopedics'), ('dermatology', 'Dermatology'), ('internal_medicine', 'Internal Medicine'), ('surgery', 'Surgery'), ('radiology', 'Radiology'), ('pathology', 'Pathology'), ('anesthesiology', 'Anesthesiology'), ('emergency_medicine', 'Emergency Medicine'), ('family_medicine', 'Family Medicine'), ('psychiatry', 'Psychiatry'), ('oncology', 'Oncology'), ('gastroenterology', 'Gastroenterology')], max_length=50),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending'), ('suspended', 'Suspended'), ('on_leave', 'On Leave')], default='active', max_length=20),
        ),
        migrations.CreateModel(
            name='DoctorAppointment',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('patient_id', models.CharField(max_length=50)),
                ('appointment_date', models.DateTimeField()),
                ('duration_minutes', models.IntegerField(default=30)),
                ('appointment_type', models.CharField(choices=[('consultation', 'Consultation'), ('follow_up', 'Follow-up'), ('emergency', 'Emergency'), ('procedure', 'Procedure'), ('telemedicine', 'Telemedicine')], default='consultation', max_length=20)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='scheduled', max_length=20)),
                ('reason', models.TextField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='DoctorManagement.doctor')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_appointments', to='superadmin.tenant')),
            ],
            options={
                'ordering': ['appointment_date'],
            },
        ),
        migrations.CreateModel(
            name='PatientRecord',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('patient_id', models.CharField(max_length=50)),
                ('visit_date', models.DateTimeField()),
                ('chief_complaint', models.TextField()),
                ('diagnosis', models.TextField(blank=True, null=True)),
                ('treatment_plan', models.TextField(blank=True, null=True)),
                ('prescriptions', models.JSONField(blank=True, default=list)),
                ('follow_up_required', models.BooleanField(default=False)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_records', to='DoctorManagement.doctor')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_records', to='superadmin.tenant')),
            ],
            options={
                'ordering': ['-visit_date'],
            },
        ),
        migrations.CreateModel(
            name='TestRequest',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('patient_id', models.CharField(max_length=50)),
                ('test_type', models.CharField(max_length=100)),
                ('test_description', models.TextField()),
                ('priority', models.CharField(choices=[('routine', 'Routine'), ('urgent', 'Urgent'), ('stat', 'STAT'), ('emergency', 'Emergency')], default='routine', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned to Technician'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('requested_date', models.DateTimeField(auto_now_add=True)),
                ('required_date', models.DateTimeField()),
                ('technician_notes', models.TextField(blank=True, null=True)),
                ('doctor_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_requests', to='DoctorManagement.doctor')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_requests', to='superadmin.tenant')),
            ],
            options={
                'ordering': ['-requested_date'],
            },
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('patient_id', models.CharField(max_length=50)),
                ('result_data', models.JSONField()),
                ('result_summary', models.TextField()),
                ('status', models.CharField(choices=[('pending_review', 'Pending Review'), ('reviewed', 'Reviewed'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending_review', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('doctor_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='DoctorManagement.doctor')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='superadmin.tenant')),
                ('test_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='DoctorManagement.testrequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
