# Generated by Django 5.2.3 on 2025-09-27 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('superadmin', '0002_databasebackup_globalnotification_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestPricing',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('test_name', models.CharField(max_length=255)),
                ('test_code', models.CharField(max_length=50, unique=True)),
                ('category', models.CharField(choices=[('blood_tests', 'Blood Tests'), ('urine_tests', 'Urine Tests'), ('imaging', 'Imaging'), ('microbiology', 'Microbiology'), ('pathology', 'Pathology'), ('cardiology', 'Cardiology'), ('neurology', 'Neurology'), ('pulmonology', 'Pulmonology'), ('endocrinology', 'Endocrinology'), ('immunology', 'Immunology')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('pricing_type', models.CharField(choices=[('standard', 'Standard'), ('premium', 'Premium'), ('express', 'Express'), ('bulk', 'Bulk'), ('insurance', 'Insurance')], default='standard', max_length=20)),
                ('turnaround_time', models.CharField(blank=True, max_length=100, null=True)),
                ('sample_type', models.CharField(blank=True, max_length=100, null=True)),
                ('preparation_instructions', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('effective_date', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('created_by', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_pricing', to='superadmin.tenant')),
            ],
            options={
                'ordering': ['test_name'],
                'unique_together': {('test_code', 'tenant')},
            },
        ),
        migrations.CreateModel(
            name='TestPricingDiscount',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('discount_name', models.CharField(max_length=255)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed_amount', 'Fixed Amount')], max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('minimum_quantity', models.IntegerField(default=1)),
                ('valid_from', models.DateField()),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_discounts', to='superadmin.tenant')),
                ('test_pricing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='TestPricing.testpricing')),
            ],
            options={
                'ordering': ['-valid_from'],
            },
        ),
    ]
