# Generated by Django 5.2.5 on 2025-09-27 15:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Receipts', '0001_initial'),
        ('superadmin', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('patient_name', models.CharField(max_length=255)),
                ('patient_id', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('generated', 'Generated'), ('printed', 'Printed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('generated_date', models.DateField(auto_now_add=True)),
                ('generated_time', models.TimeField(auto_now_add=True)),
                ('services', models.JSONField(default=list)),
                ('doctor', models.CharField(max_length=255)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('insurance', 'Insurance'), ('check', 'Check'), ('bank_transfer', 'Bank Transfer')], default='cash', max_length=20)),
                ('print_count', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='superadmin.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BillingTransaction',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('payment', 'Payment'), ('refund', 'Refund'), ('adjustment', 'Adjustment'), ('discount', 'Discount')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('processed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_transactions', to='superadmin.tenant')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='Receipts.receipt')),
            ],
            options={
                'ordering': ['-processed_at'],
            },
        ),
    ]
