# Generated by Django 5.2.5 on 2025-09-23 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='timezone',
            field=models.CharField(choices=[('UTC', 'UTC (Coordinated Universal Time)'), ('America/New_York', 'Eastern Time (ET)'), ('America/Chicago', 'Central Time (CT)'), ('America/Denver', 'Mountain Time (MT)'), ('America/Los_Angeles', 'Pacific Time (PT)'), ('America/Anchorage', 'Alaska Time (AKT)'), ('Pacific/Honolulu', 'Hawaii Time (HST)'), ('Europe/London', 'London (GMT/BST)'), ('Europe/Paris', 'Paris (CET/CEST)'), ('Europe/Berlin', 'Berlin (CET/CEST)'), ('Europe/Rome', 'Rome (CET/CEST)'), ('Europe/Madrid', 'Madrid (CET/CEST)'), ('Asia/Tokyo', 'Tokyo (JST)'), ('Asia/Shanghai', 'Shanghai (CST)'), ('Asia/Kolkata', 'Mumbai/Delhi (IST)'), ('Asia/Dubai', 'Dubai (GST)'), ('Australia/Sydney', 'Sydney (AEST/AEDT)'), ('Australia/Melbourne', 'Melbourne (AEST/AEDT)'), ('Africa/Cairo', 'Cairo (EET)'), ('Africa/Johannesburg', 'Johannesburg (SAST)'), ('America/Sao_Paulo', 'São Paulo (BRT)'), ('America/Mexico_City', 'Mexico City (CST)'), ('America/Toronto', 'Toronto (EST/EDT)'), ('America/Vancouver', 'Vancouver (PST/PDT)')], default='UTC', max_length=50),
        ),
    ]
