# Generated by Django 5.2.3 on 2025-09-27 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('superadmin', '0002_databasebackup_globalnotification_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('laboratory', 'Laboratory'), ('imaging', 'Imaging'), ('sterilization', 'Sterilization'), ('monitoring', 'Monitoring'), ('surgical', 'Surgical'), ('diagnostic', 'Diagnostic')], max_length=50)),
                ('category', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('manufacturer', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('operational', 'Operational'), ('maintenance', 'Maintenance'), ('out_of_service', 'Out of Service'), ('retired', 'Retired')], default='operational', max_length=20)),
                ('location', models.CharField(max_length=255)),
                ('purchase_date', models.DateField()),
                ('warranty_expiry', models.DateField(blank=True, null=True)),
                ('last_maintenance', models.DateField(blank=True, null=True)),
                ('next_maintenance', models.DateField(blank=True, null=True)),
                ('maintenance_interval', models.CharField(blank=True, max_length=50, null=True)),
                ('responsible', models.CharField(blank=True, max_length=255, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('condition', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('needs_repair', 'Needs Repair')], default='good', max_length=20)),
                ('created_by', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='superadmin.tenant')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('serial_number', 'tenant')},
            },
        ),
    ]
