# Generated by Django 5.2.5 on 2025-08-30 18:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient', models.CharField(max_length=100)),
                ('test', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Received', 'Received'), ('Processing', 'Processing'), ('Completed', 'Completed'), ('Pending', 'Pending'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('priority', models.CharField(choices=[('Routine', 'Routine'), ('Urgent', 'Urgent'), ('STAT', 'STAT')], default='Routine', max_length=20)),
                ('collection_date', models.DateField(blank=True, null=True)),
                ('assigned_to', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=255)),
                ('test_type', models.CharField(max_length=100)),
                ('priority', models.CharField(choices=[('Normal', 'Normal'), ('Urgent', 'Urgent'), ('Critical', 'Critical')], default='Normal', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('date_requested', models.DateField(default=datetime.date.today)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted', models.BooleanField(default=False)),
            ],
        ),
    ]
